import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";

/** Overridable for tests — M0DESK_DB_PATH points at a throwaway file. */
function dbPath(): string {
  return (
    process.env.M0DESK_DB_PATH ??
    path.join(process.cwd(), "data", "m0desk.db")
  );
}

function dataDir(): string {
  return path.dirname(dbPath());
}

const SCHEMA_PATH = path.join(process.cwd(), "src/lib/db/schema.sql");

let db: DatabaseSync | null = null;

/** Singleton SQLite connection. Initializes schema on first use. */
export function getDb(): DatabaseSync {
  if (!db) {
    mkdirSync(dataDir(), { recursive: true });
    db = new DatabaseSync(dbPath());
    db.exec("PRAGMA foreign_keys = ON;");
    db.exec(readFileSync(SCHEMA_PATH, "utf8"));
  }
  return db;
}

/** Test helper: close the singleton and point it at a fresh database. */
export function resetDbForTests(): void {
  try {
    db?.close();
  } catch {
    // already closed
  }
  db = null;
  try {
    rmSync(dbPath(), { force: true });
  } catch {
    // fresh path
  }
}

export function parseTags(raw: string): string[] {
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.map(String) : [];
  } catch {
    return [];
  }
}

export function toTags(tags: string[]): string {
  return JSON.stringify(tags.filter(Boolean));
}

/**
 * node:sqlite returns rows with a null prototype, which React cannot
 * serialize into Client Components. Always spread rows into plain objects.
 */
export function allPlain<T = Record<string, unknown>>(
  sql: string,
  ...params: (string | number | null)[]
): T[] {
  const rows = getDb().prepare(sql).all(...params);
  return rows.map((r) => ({ ...(r as Record<string, unknown>) })) as T[];
}

export function getPlain<T = Record<string, unknown>>(
  sql: string,
  ...params: (string | number | null)[]
): T | null {
  const row = getDb().prepare(sql).get(...params);
  return row ? ({ ...(row as Record<string, unknown>) } as T) : null;
}

/** ISO-8601 UTC now, same format the schema triggers produce. */
export function nowIso(): string {
  return new Date().toISOString();
}

/**
 * TEXT primary keys are generated by SQLite defaults, so lastInsertRowid is
 * the integer rowid, not the id column. Fetch the real id back after insert.
 */
export function insertedId(
  db: DatabaseSync,
  table: string,
  lastRowid: number | bigint,
): string {
  const row = db
    .prepare(`SELECT id FROM ${table} WHERE rowid = ?`)
    .get(lastRowid) as { id: string } | undefined;
  return row?.id ?? String(lastRowid);
}
